server_name: transfer1

kafka:
  address: [127.0.0.1:9092]

etcd:
  address: [127.0.0.1:2379]

elasticsearch:
  url: http://127.0.0.1:9200
  etcd_key: server-conf
  chan_max_size: 100000
  sender_nums: 4
  enabled_es_offset: false
